services:
    jl_n2nl.listener.insert_tags:
        class: Jl\NewsToNewsletterBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"
        public: true
    jl_n2nl.listener.new_user:
        class: Jl\NewsToNewsletterBundle\EventListener\NewUserListener
        arguments:
            - "@contao.framework"
            - "@database_connection"
        public: true
