services:
    srhinow_n2nl.listener.insert_tags:
        class: Srhinow\NewsToNewsletterBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"
        public: true
    srhinow_n2nl.listener.new_user:
        class: Srhinow\NewsToNewsletterBundle\EventListener\NewUserListener
        arguments:
            - "@contao.framework"
            - "@database_connection"
        public: true
